name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'doc/**'
      - 'LICENSE'
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: make test
        shell: bash  # Use bash shell for both Ubuntu and Windows (Git Bash is used on Windows)
